### ISSUE TITLE
Hitting search button yields empty box from top

### ISSUE THREAD

**Issue by ghost** [manni-app/manni-ios#1]
## Information

Version: 2.4
Device: iPhone SE
iOS Version: 12.1.4 (16D57)

## Actual behavior 

When hitting the search button when one of the search fields is empty, results in an empty bar being shown from the top showing no information. The bar cannot be removed and the app has to be force closed. 

![IMG_0532](https://user-images.githubusercontent.com/8080309/54083946-d6074980-432a-11e9-8c7f-4762c954cab1.PNG)

**Comment by PhilippMatthes** [comment]
Thanks for opening this issue. I will look into this asap.
